name: Generate Release Changelog
on:
  push:
    tags:
      - '*'
      
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
               "categories": [
                {
                  "title": "## Features",
                  "labels": ["feature"]
                },
                {
                  "title": "## Fixes",
                  "labels": ["fix"]
                },
                {
                  "key": "tests",
                  "title": "## Improvements",
                  "labels": ["test"]
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
