name: i18n check

on: 
  workflow_call:

jobs:
  i18n-check:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v3
      
     - uses: r-lib/actions/setup-r@v2
   
     - name: Setup tools
       run: |
         install.packages(c("cli", "potools"))
       shell: Rscript {0}
       
     - name: Check current directory
       run: pwd
     - name: Download the script
       run: |
         # stupid but stupid but simple access script:)
         curl -o $PWD/i18nCheck.R https://raw.githubusercontent.com/shun2wang/jasp-actions/tr_unittest/translations/i18nCheck.R
     - name: Give script permissions
       run: chmod +x $PWD/i18nCheck.R
       
     - name: Run i18n check
       run: Rscript $PWD/i18nCheck.R
