name: i18n check

on: 
  workflow_call:

jobs:
  i18n-check:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v2
      
     - uses: r-lib/actions/setup-r@v2
   
     - name: Setup tools
       run: |
         install.packages(c("cli", "potools"))
       shell: Rscript {0}
     
     - name: Run i18n check
       run: |
          Rscript ${{ github.action_path }}/translations/i18nCheck.R
       shell: bash
